"""Fast point cloud I/O, distances, ICP and filters from the CloudAnalyzer Rust core.

Points are ``(N, 3)`` float64 NumPy arrays. Heavy functions release the GIL
and use all cores.
"""

from ._core import (
    BagMessages,
    BagReader,
    LidarOdometry,
    PoseGraph,
    Scan,
    __version__,
    audit_vector_map_quality,
    audit_vector_map_quality_details,
    audit_vector_map_ground_consensus_details,
    build_vector_map,
    calibrate_ups,
    changed_objects,
    cloud_to_mesh,
    connect_vector_map_junctions,
    discover_vector_map_features,
    edit_vector_map_relations,
    propose_vector_map_relations,
    ground_csf,
    icp,
    m3c2,
    measure_vector_map_signal,
    measure_vector_map_crosswalk,
    measure_vector_map_signal_points,
    nearest_distances,
    normals,
    profile,
    read,
    read_mesh,
    statistical_outliers,
    volume,
    voxel_subsample,
)
from ._copc import read_copc
from ._spatial import CopcBatch, CopcCancelled, CopcLimits, CopcNode, CopcStream, iter_copc_batches

__all__ = [
    "BagMessages",
    "BagReader",
    "CopcBatch",
    "CopcCancelled",
    "CopcLimits",
    "CopcNode",
    "CopcStream",
    "LidarOdometry",
    "PoseGraph",
    "Scan",
    "__version__",
    "audit_vector_map_quality",
    "audit_vector_map_quality_details",
    "audit_vector_map_ground_consensus_details",
    "build_vector_map",
    "calibrate_ups",
    "changed_objects",
    "cloud_to_mesh",
    "connect_vector_map_junctions",
    "discover_vector_map_features",
    "edit_vector_map_relations",
    "propose_vector_map_relations",
    "ground_csf",
    "icp",
    "iter_copc_batches",
    "m3c2",
    "measure_vector_map_signal",
    "measure_vector_map_crosswalk",
    "measure_vector_map_signal_points",
    "nearest_distances",
    "normals",
    "profile",
    "read",
    "read_copc",
    "read_mesh",
    "statistical_outliers",
    "volume",
    "voxel_subsample",
]
