// Production UI capture on existing Autoware survey regions. Boxes, classification
// and lane associations are explicit operator inputs; imported context stays distinct.
import { expect, test } from "@playwright/test";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const MAP = process.env.VECTOR_MAP_PLANNING_DIR;
const JUNCTION = process.env.VECTOR_MAP_JUNCTION_DIR;
const FRAMES = fileURLToPath(new URL("../media-frames/vector-map-features/", import.meta.url));
test.use({ viewport: { width:1280,height:760 } });
test("vector map point features README GIF on the real planning survey", async ({page}) => {
  test.skip(!MAP || !JUNCTION,"Set external planning and junction-ablation directories");
  test.setTimeout(240000); mkdirSync(FRAMES,{recursive:true});
  const input = JSON.parse(readFileSync(`${JUNCTION}/input.json`,"utf8"));
  expect(input.lanes.length).toBe(72);
  const head = input.traffic_signals.find((s:any)=>s.id===353);
  const rule = input.regulatory_elements.find((r:any)=>r.id===1008);
  expect(head).toBeTruthy(); expect(rule.rule.signals).toEqual([353]); expect(rule.lanes ?? []).toEqual([]);
  // Only the already surveyed head and its empty-lanes rule are ablated. Neither
  // reference housing nor reference paint corners are inputs to either fit.
  input.traffic_signals=input.traffic_signals.filter((s:any)=>s.id!==353);
  input.regulatory_elements=input.regulatory_elements.filter((r:any)=>r.id!==1008);
  const errors:string[]=[]; page.on("pageerror",e=>errors.push(String(e)));
  await page.goto("/");
  await page.locator("#file-input").setInputFiles(`${MAP}/pointcloud_map.pcd`);
  await expect(page.locator("#status")).toContainText("Loaded pointcloud_map.pcd",{timeout:120000});
  await page.locator("#edl").uncheck(); await page.locator("#point-size").fill("2");
  await page.locator("#vm-file").setInputFiles({name:"point-features.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(input))});
  await expect(page.locator("#status")).toContainText("Opened point-features.json: 72 lanes");
  await page.locator("#vector-map-panel").getByText("Map display",{exact:true}).click();
  for(const key of ["surfaces","directions","markings","regulations","labels"]) await page.locator(`#vm-show-${key}`).uncheck();
  await page.locator("#vm-plan").click();
  await page.evaluate(()=>{const el=document.createElement("div");el.id="capture-caption";el.style.cssText="position:fixed;left:300px;top:92px;padding:10px 16px;background:#111a29f0;color:white;font:600 19px sans-serif;border:1px solid #3a5975;border-radius:8px;z-index:1000;pointer-events:none";document.body.append(el);});
  const frames:{name:string;duration:number}[]=[];
  const shot=async(text:string,duration=1.7)=>{await page.locator("#capture-caption").evaluate((el,text)=>{el.textContent=text;},text);await page.waitForTimeout(120);const name=`${String(frames.length).padStart(3,"0")}.png`;await page.screenshot({path:`${FRAMES}/${name}`});frames.push({name,duration});};
  let exports=0;
  const exportMap=async()=>{if(exports>0 && exports%4===0) await page.waitForTimeout(1100);exports++;const wait=page.waitForEvent("download",d=>d.suggestedFilename()==="lanelet2_map.osm");await page.locator("#vm-export").click();const path=await(await wait).path();if(!path)throw new Error("Export missing");return readFileSync(path,"utf8");};
  const before=await exportMap();
  await page.locator("#vm-crosswalk-measure summary").click();
  for(const [edge,values] of [["min",[3882,73743,18.5]],["max",[3899,73764,20.5]]] as const) for(const [i,axis] of ["x","y","z"].entries()) await page.locator(`#vm-crosswalk-${edge}-${axis}`).fill(String(values[i]));
  await page.locator("#vm-crosswalk-brightness").fill("65"); await page.locator("#vm-crosswalk-lanes").fill("133,134");
  const paintPreview=async()=>{await page.locator("#vm-crosswalk-preview").click();await expect(page.locator("#status")).toContainText("paint candidates");await expect(page.locator("#vm-crosswalk-report")).toContainText("7434 box points; 5568 ground; rgb_min_channel");await expect(page.locator("#vm-crosswalk-candidates")).toContainText("4 bands");};
  await paintPreview(); await page.locator("#vm-crosswalk-inspect").click();
  await expect(page.locator("#status")).toContainText("paint-box points copied with their attributes");
  await page.locator("#fit").click(); await page.waitForTimeout(700);
  await shot("1. Inspect actual RGB paint · operator-selected ROI",2);
  await paintPreview(); await page.locator("input[name=crosswalk-candidate]").first().check(); await page.waitForTimeout(500);
  await shot("2. Four observed bands · missing paint stays missing",2);
  expect(await exportMap()).toBe(before);
  await page.locator("#vm-crosswalk-add").click(); await expect(page.locator("#status")).toContainText("Measured crossing");
  await page.locator("#vm-show-regulations").check();
  const crossing=await exportMap(); expect(crossing).toContain('v="point_cloud_brightness_stripes"');
  await shot("3. Confirm crossing and lane IDs · add measured outline");
  await page.locator("#vm-crosswalk-measure summary").click(); await page.locator("#vm-feature-editor summary").click();
  await expect(page.locator("#vm-feature-height-row")).toBeHidden();
  const x=Number(await page.locator("#vm-feature-x").inputValue());
  await page.locator("#vm-feature-x").fill(String(x+.1)); await page.locator("#vm-feature-apply").click();
  await expect(page.locator("#status")).toContainText("edited.");
  await page.locator("#vm-feature-drag").click();
  const editedCrossing=await exportMap(); expect(editedCrossing).not.toBe(crossing);
  const bands=(xml:string)=>xml.match(/<tag k="cloudanalyzer_paint_bands" v="[^"]*"/g);
  expect(bands(editedCrossing)).toEqual(bands(crossing));
  await shot("4. Refine a vertex · observed paint stays fixed");
  await page.keyboard.press("Escape"); await page.locator("#vm-undo").click(); expect(await exportMap()).toBe(crossing);
  await shot("Undo restores geometry and provenance exactly",1.3);
  await page.locator("#vm-feature-editor summary").click(); await page.locator("#vm-show-regulations").uncheck();
  await page.locator("#vector-map-panel").getByText("Measure a signal from points",{exact:true}).click();
  // Separate signal region in the same survey; this is not the junction's
  // automatically identified signal, and controlled lane 85 remains a draft.
  for(const [edge,values] of [["min",[3832.1,73770.1,24.74]],["max",[3833.9,73771.4,25.27]]] as const) for(const [i,axis] of ["x","y","z"].entries()) await page.locator(`#vm-signal-${edge}-${axis}`).fill(String(values[i]));
  await page.locator("#vm-signal-lanes").fill("85"); await page.locator('[data-view="iso"]').click();
  await page.locator("#vm-signal-preview").click(); await expect(page.locator("#status")).toContainText("Signal geometry measured");
  await page.locator("#vm-signal-inspect").click(); await expect(page.locator("#status")).toContainText("61 box points copied");
  await page.locator("#vm-signal-preview").click(); await expect(page.locator("#status")).toContainText("Signal geometry measured");
  await expect(page.locator("#vm-signal-report")).toContainText("61 points");
  await page.locator("#point-size").fill("5");
  const canvas=(await page.locator("#viewport > canvas").boundingBox())!;
  await page.mouse.move(canvas.x+canvas.width/2,canvas.y+canvas.height/2);
  await page.mouse.wheel(0,-1800); await page.waitForTimeout(800);
  await shot("5. Another ROI · measure a user-identified signal head",2.3);
  expect(await exportMap()).toBe(crossing);
  await page.locator("#vm-signal-add").click(); await expect(page.locator("#status")).toContainText("Measured signal");
  const signal=await exportMap(); expect(signal).toContain('v="point_cloud_box_fit"');
  const pointSignals=signal.match(/k="cloudanalyzer_geometry_source" v="point_cloud_box_fit"/g);expect(pointSignals?.length).toBe(1);
  await page.locator("#vm-show-regulations").check();
  await page.locator("#vector-map-panel").getByText("Measure a signal from points",{exact:true}).click(); await page.locator("#vm-feature-editor summary").click();
  await expect(page.locator("#vm-feature-height-row")).toBeVisible();
  await shot("6. Add housing geometry · no lamps or states invented");
  const z=Number(await page.locator("#vm-feature-z").inputValue()),height=Number(await page.locator("#vm-feature-height").inputValue());
  await page.locator("#vm-feature-z").fill(String(z+.02)); await page.locator("#vm-feature-height").fill(String(height+.02)); await page.locator("#vm-feature-apply").click();
  await expect(page.locator("#status")).toContainText("edited."); await page.locator("#vm-feature-drag").click();
  const editedSignal=await exportMap();expect(editedSignal).toContain('v="point_cloud_box_fit_user_edited"');
  await shot("Adjust XYZ and housing height · keep lane assignments");
  await page.keyboard.press("Escape");await page.locator("#vm-undo").click();expect(await exportMap()).toBe(signal);
  await shot("7. Undo · save Lanelet2 with MGRS metadata",2);
  await page.locator("#vm-file").setInputFiles({name:"point-features.osm",mimeType:"application/xml",buffer:Buffer.from(signal)});
  await expect(page.locator("#status")).toContainText("Opened point-features.osm: 72 lanes");
  await expect(page.locator("#vm-undo")).toBeDisabled();
  const reopened=await exportMap();expect(bands(reopened)).toEqual(bands(signal));expect(reopened).toContain('v="point_cloud_box_fit"');
  expect(errors).toEqual([]);
  writeFileSync(`${FRAMES}/verification.json`,JSON.stringify({points:1757841,paintBoxPoints:7434,groundPoints:5568,observedBands:4,signalPoints:61,explicitPaintLanes:[133,134],explicitSignalLanes:[85],ablatedSignal:353,ablatedRule:1008,previewUnchanged:true,observationsPreserved:true,exactEditUndo:true,osmRoundtrip:true,errors},null,2));
  writeFileSync(`${FRAMES}/frames.json`,JSON.stringify(frames,null,2));
  writeFileSync(`${FRAMES}/concat.txt`,frames.map(f=>`file '${f.name}'\nduration ${f.duration}\n`).join("")+`file '${frames.at(-1)!.name}'\n`);
});
