// Temporary, not committed: KITTI 09 joined with 10 (both 2011-09-30), compared by M3C2.
import { expect, test } from "@playwright/test";
const K = process.env.KITTI_DIR!;
test.setTimeout(3_600_000);
test("sessions", async ({ page }) => {
  const status = page.locator("#status");
  const log = async (what: string) => console.log(what, "|", await status.textContent(), "|", await page.locator("#memory").textContent());
  await page.goto("/");
  await page.locator("#pg-folder-input").setInputFiles(`${K}/09/velodyne`);
  await expect(status).toContainText("Opened kiss_poses.txt", { timeout: 3_000_000 });
  await page.locator("#pose-graph-panel summary", { hasText: "Find loops automatically" }).click();
  await page.locator("#pg-find").click();
  await expect(status).toContainText(/Added \d+ of/, { timeout: 600_000 });
  await log("LOOPS09");
  await page.locator("#pose-graph-panel summary", { hasText: "Join another graph" }).click();
  await page.locator("#pg-merge-here").fill("1165");
  await page.locator("#pg-merge-there").fill("660");
  await page.locator("#pg-merge-input").setInputFiles(`${K}/10/velodyne`);
  await expect(status).toContainText(/Joined|failed/, { timeout: 3_000_000 });
  await log("JOIN");
  await page.locator("#pg-find").click();
  await expect(status).toContainText(/Added \d+ of|No loop/, { timeout: 600_000 });
  await log("LOOPS");
  await page.locator("#pose-graph-panel summary", { hasText: "IMU gravity" }).click();
  await page.locator("#pg-gravity-input").setInputFiles(`${K}/joined0910`);
  await expect(status).toContainText(/Gravity tied|failed/, { timeout: 600_000 });
  await log("GRAVITY");
  await page.locator("#pg-map-voxel").fill("0.5");
  await page.locator("#pg-parts").click();
  await expect(status).toContainText(/M3C2 at|failed/, { timeout: 1_800_000 });
  await log("M3C2");
  console.log("CHANGES", await page.locator("#pg-changes-hint").textContent(), "|", (await page.locator("#pg-change-list").textContent())?.slice(0, 400));
  const save = async (name: string) => {
    const download = page.waitForEvent("download");
    await page.locator("#pg-save-kitti").click();
    await (await download).saveAs(`${K}/joined0910/${name}`);
  };
  await save("app_joined.txt");
  await page.locator("#pg-dynamic").click();
  await expect(status).toContainText(/dynamic points of|failed/, { timeout: 1_800_000 });
  await log("DYNAMIC");
  await page.locator("[data-view=top]").click();
  await page.locator("#fit").click();
  await page.waitForTimeout(2500);
  await page.screenshot({ path: `${K}/joined0910/m3c2.png` });
  await page.locator("#point-size").fill("3");
  const box = (await page.locator("#viewport > canvas").boundingBox())!;
  await page.mouse.move(box.x + box.width * 0.45, box.y + box.height * 0.45);
  for (let i = 0; i < 8; i++) await page.mouse.wheel(0, -300);
  await page.waitForTimeout(2500);
  await page.screenshot({ path: `${K}/joined0910/m3c2-zoom.png` });
  await page.locator("#pg-change-list li .link").first().click();
  for (let i = 0; i < 6; i++) await page.mouse.wheel(0, -300);
  await page.waitForTimeout(2500);
  await page.screenshot({ path: `${K}/joined0910/change1.png` });
});
