"""Shared fixtures for CloudAnalyzer tests."""

import json
from pathlib import Path

import numpy as np
import open3d as o3d
import pytest


def _benchmark_check(
    check_id: str,
    kind: str,
    *,
    passed: bool,
    summary: dict,
    artifact_dir: Path,
    reasons: list[str] | None = None,
) -> dict:
    """Return a realistic, filesystem-backed ``ca check`` entry."""
    report = artifact_dir / f"{check_id}.html"
    result = artifact_dir / f"{check_id}.json"
    report.write_text(f"<html><title>{check_id}</title></html>\n", encoding="utf-8")
    result.write_text(json.dumps({"quality_gate": {"passed": passed}}), encoding="utf-8")
    return {
        "id": check_id,
        "kind": kind,
        "passed": passed,
        "report_path": str(report),
        "json_path": str(result),
        "summary": {**summary, "passed": passed},
        "result": {
            "quality_gate" if kind != "run" else "overall_quality_gate": {
                "passed": passed,
                "reasons": reasons or [],
            }
        },
    }


@pytest.fixture
def public_benchmark_summary_paths(tmp_path: Path) -> tuple[Path, Path]:
    """Create compact pass/regression summaries shaped like the public pack.

    The actual Stanford Bunny pack is intentionally gitignored and generated by
    its dedicated integration workflow. Unit tests use this local equivalent so
    a clean checkout does not need a network download or Open3D rendering.
    """
    artifact_dir = tmp_path / "benchmark-artifacts"
    artifact_dir.mkdir()

    pass_checks = [
        _benchmark_check("mapping-postprocess", "artifact", passed=True,
                         summary={"auc": 1.0, "chamfer_distance": 0.0015}, artifact_dir=artifact_dir),
        _benchmark_check("localization-run", "trajectory", passed=True,
                         summary={"ate_rmse": 0.003, "rpe_rmse": 0.002,
                                  "drift_endpoint": 0.004, "coverage_ratio": 1.0},
                         artifact_dir=artifact_dir),
        _benchmark_check("perception-output", "artifact", passed=True,
                         summary={"auc": 0.995, "chamfer_distance": 0.003}, artifact_dir=artifact_dir),
        _benchmark_check("integrated-run", "run", passed=True,
                         summary={"map_auc": 1.0, "map_chamfer_distance": 0.0015,
                                  "trajectory_ate_rmse": 0.003,
                                  "trajectory_rpe_rmse": 0.002,
                                  "trajectory_drift_endpoint": 0.004,
                                  "coverage_ratio": 1.0},
                         artifact_dir=artifact_dir),
    ]
    fail_checks = [
        _benchmark_check("mapping-postprocess", "artifact", passed=False,
                         summary={"auc": 0.5282, "chamfer_distance": 0.0394},
                         artifact_dir=artifact_dir,
                         reasons=["AUC 0.5282 < min_auc 0.9700"]),
        _benchmark_check("localization-run", "trajectory", passed=False,
                         summary={"ate_rmse": 0.08, "rpe_rmse": 0.04,
                                  "drift_endpoint": 0.12, "coverage_ratio": 0.812},
                         artifact_dir=artifact_dir, reasons=["ATE RMSE exceeds max_ate"]),
        _benchmark_check("perception-output", "artifact", passed=False,
                         summary={"auc": 0.61, "chamfer_distance": 0.032},
                         artifact_dir=artifact_dir, reasons=["AUC below min_auc"]),
        _benchmark_check("integrated-run", "run", passed=False,
                         summary={"map_auc": 0.5282, "map_chamfer_distance": 0.0394,
                                  "trajectory_ate_rmse": 0.08,
                                  "trajectory_rpe_rmse": 0.04,
                                  "trajectory_drift_endpoint": 0.12,
                                  "coverage_ratio": 0.812},
                         artifact_dir=artifact_dir, reasons=["Integrated quality gate failed"]),
    ]

    def write(name: str, checks: list[dict], passed: bool) -> Path:
        path = tmp_path / name
        failed_ids = [check["id"] for check in checks if not check["passed"]]
        payload = {
            "project": "public-benchmark-pass" if passed else "public-benchmark-regression",
            "summary": {
                "total_checks": len(checks),
                "passed_checks": len(checks) - len(failed_ids),
                "failed_checks": len(failed_ids),
                "failed_check_ids": failed_ids,
                "passed": passed,
            },
            "checks": checks,
        }
        path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        return path

    return write("suite-pass.summary.json", pass_checks, True), write(
        "suite-regression.summary.json", fail_checks, False
    )


@pytest.fixture
def simple_pcd():
    """A small point cloud with 100 points in a unit cube."""
    pcd = o3d.geometry.PointCloud()
    rng = np.random.default_rng(42)
    pcd.points = o3d.utility.Vector3dVector(rng.random((100, 3)))
    return pcd


@pytest.fixture
def shifted_pcd(simple_pcd):
    """Same shape as simple_pcd but shifted by (0.1, 0, 0)."""
    points = np.asarray(simple_pcd.points).copy()
    points[:, 0] += 0.1
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)
    return pcd


@pytest.fixture
def identical_pcd(simple_pcd):
    """Exact copy of simple_pcd."""
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(np.asarray(simple_pcd.points).copy())
    return pcd


@pytest.fixture
def sample_pcd_file(tmp_path, simple_pcd):
    """Write a PCD file and return its path."""
    path = tmp_path / "sample.pcd"
    o3d.io.write_point_cloud(str(path), simple_pcd)
    return str(path)


@pytest.fixture
def source_and_target_files(tmp_path, simple_pcd, shifted_pcd):
    """Write source and target PCD files, return (source_path, target_path)."""
    src = tmp_path / "source.pcd"
    tgt = tmp_path / "target.pcd"
    o3d.io.write_point_cloud(str(src), simple_pcd)
    o3d.io.write_point_cloud(str(tgt), shifted_pcd)
    return str(src), str(tgt)
