#!/usr/bin/env python3
"""Build a public static demo bundle for GitHub Pages."""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

import numpy as np
import open3d as o3d

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = REPO_ROOT / "cloudanalyzer"
if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))

from public_benchmark_assets import (
    BUNNY_ARCHIVE_URL,
    BUNNY_SOURCE_PAGE,
    download_bunny_mesh,
    make_trajectory_rows,
    rotation_matrix,
    write_csv_trajectory,
)
from ca.web import export_static_bundle


def build_public_demo(output_dir: Path, max_points: int) -> dict:
    mesh = download_bunny_mesh()
    vertices = np.asarray(mesh.vertices, dtype=float)
    center = np.mean(vertices, axis=0)
    extent = np.max(vertices, axis=0) - np.min(vertices, axis=0)

    source_cloud = o3d.geometry.PointCloud()
    source_cloud.points = o3d.utility.Vector3dVector(vertices)

    centered = vertices - center[None, :]
    rotation = rotation_matrix(z_degrees=4.5, x_degrees=-2.0)
    reference_points = centered @ rotation.T
    reference_points[:, 0] *= 1.008
    reference_points[:, 1] *= 0.992
    reference_points += center[None, :] + np.array(
        [extent[0] * 0.035, -extent[1] * 0.018, extent[2] * 0.02],
        dtype=float,
    )
    reference_cloud = o3d.geometry.PointCloud()
    reference_cloud.points = o3d.utility.Vector3dVector(reference_points)

    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_root = Path(tmp_dir)
        source_path = tmp_root / "stanford_bunny_source.pcd"
        reference_path = tmp_root / "stanford_bunny_reference.pcd"
        estimated_traj_path = tmp_root / "stanford_bunny_traj.csv"
        reference_traj_path = tmp_root / "stanford_bunny_traj_ref.csv"

        o3d.io.write_point_cloud(str(source_path), source_cloud)
        o3d.io.write_point_cloud(str(reference_path), reference_cloud)
        write_csv_trajectory(
            estimated_traj_path,
            make_trajectory_rows(
                center,
                extent,
                phase=0.12,
                radial_wobble=0.035,
                vertical_wobble=0.08,
            ),
        )
        write_csv_trajectory(
            reference_traj_path,
            make_trajectory_rows(
                center,
                extent,
                phase=0.0,
                radial_wobble=0.0,
                vertical_wobble=0.05,
            ),
        )

        result = export_static_bundle(
            [str(source_path), str(reference_path)],
            output_dir=str(output_dir),
            max_points=max_points,
            heatmap=True,
            trajectory_path=str(estimated_traj_path),
            trajectory_reference_path=str(reference_traj_path),
            trajectory_max_time_delta=0.2,
        )

    attribution = "\n".join(
        [
            "# Stanford Bunny Demo Attribution",
            "",
            "Source mesh: The Stanford Bunny from the Stanford 3D Scanning Repository.",
            f"Source page: {BUNNY_SOURCE_PAGE}",
            f"Archive: {BUNNY_ARCHIVE_URL}",
            "",
            "This demo derives its source point cloud from bun_zipper.ply.",
            "The reference point cloud and both trajectories are generated by CloudAnalyzer",
            "to demonstrate heatmap inspection, progressive loading, and trajectory overlays.",
            "",
            "The Stanford repository states that the models may be used for research,",
            "mirrored or redistributed for free with credit to the Stanford Computer Graphics",
            "Laboratory, and are not for commercial use without permission.",
        ]
    )
    (output_dir / "ATTRIBUTION.md").write_text(attribution + "\n")
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the public Stanford Bunny demo bundle.")
    parser.add_argument(
        "--output",
        default="docs/demo/stanford-bunny",
        help="Output directory for the static viewer bundle",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=50_000,
        help="Viewer point budget passed to ca web-export",
    )
    args = parser.parse_args()

    result = build_public_demo(Path(args.output), max_points=args.max_points)
    print(f"Exported:     {result['output_dir']}")
    print(f"Viewer mode:  {result['viewer_mode']}")
    print(f"Data:         {result['data_json']}")
    print(f"Chunks:       {result['chunk_count']}")
    print(f"Display pts:  {result['display_points']}")


if __name__ == "__main__":
    main()
