#!/usr/bin/env python3
"""Generate the synthetic-figure8 benchmark suite under benchmarks/slam/.

This script is deterministic — running it on a clean checkout reproduces
exactly the files committed under ``benchmarks/slam/synthetic-figure8/``.

Layout produced::

    benchmarks/slam/synthetic-figure8/
    ├── suite.yaml                            # manifest (loaded by `ca benchmark`)
    ├── reference/
    │   ├── map.pcd
    │   └── trajectory.tum
    └── sample_outputs/
        ├── map_pass.pcd                      # reference + small noise; passes the gate
        └── trajectory_pass.tum
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import open3d as o3d


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = REPO_ROOT / "benchmarks" / "slam" / "synthetic-figure8"


def _planar_map(seed: int = 42) -> np.ndarray:
    """Return a ~640-point planar room with two raised box edges."""
    rng = np.random.default_rng(seed)
    xs = np.linspace(-10.0, 10.0, 20)
    ys = np.linspace(-10.0, 10.0, 20)
    xx, yy = np.meshgrid(xs, ys)
    floor = np.column_stack([xx.ravel(), yy.ravel(), np.zeros(xx.size)])
    floor += rng.normal(0, 0.005, size=floor.shape)

    # Two vertical "walls" that anchor the figure-8 visually.
    wall_x = np.linspace(-8.0, 8.0, 80)
    wall_y_pos = np.full_like(wall_x, 8.0)
    wall_y_neg = np.full_like(wall_x, -8.0)
    wall_z = np.linspace(0.0, 1.5, 6)
    wall_xs, wall_zs = np.meshgrid(wall_x, wall_z)
    wall_pos = np.column_stack(
        [wall_xs.ravel(), np.full(wall_xs.size, 8.0), wall_zs.ravel()]
    )
    wall_neg = np.column_stack(
        [wall_xs.ravel(), np.full(wall_xs.size, -8.0), wall_zs.ravel()]
    )
    wall_pos += rng.normal(0, 0.005, size=wall_pos.shape)
    wall_neg += rng.normal(0, 0.005, size=wall_neg.shape)
    del wall_y_pos, wall_y_neg  # parameter only kept for readability

    return np.vstack([floor, wall_pos, wall_neg]).astype(np.float64)


def _figure8_trajectory(n: int = 200) -> tuple[np.ndarray, np.ndarray]:
    """Return (timestamps, positions) for a planar figure-8 of ``n`` poses."""
    t = np.linspace(0.0, 2.0 * np.pi, n, endpoint=False)
    x = 5.0 * np.sin(t)
    y = 5.0 * np.sin(t) * np.cos(t)
    z = np.zeros_like(t)
    positions = np.column_stack([x, y, z])
    timestamps = np.arange(n) * 0.1
    return timestamps, positions


def _write_pcd(points: np.ndarray, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(np.asarray(points, dtype=np.float64))
    o3d.io.write_point_cloud(str(path), pcd, write_ascii=False)


def _write_tum(timestamps: np.ndarray, positions: np.ndarray, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"{ts:.6f} {x:.6f} {y:.6f} {z:.6f} 0.000000 0.000000 0.000000 1.000000"
        for ts, (x, y, z) in zip(timestamps, positions)
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


SUITE_YAML = """\
version: 1
name: synthetic-figure8
description: Tiny synthetic figure-8 trajectory with a planar room map. Use it to smoke-test `ca benchmark` without external data.
license: MIT (synthetic data generated by scripts/build_synthetic_slam_suite.py)
sequences:
  default:
    description: 200-pose figure-8 over a ~1.6k point planar room with two raised walls.
    reference_map: reference/map.pcd
    reference_trajectory: reference/trajectory.tum
sample_outputs:
  default:
    map: sample_outputs/map_pass.pcd
    trajectory: sample_outputs/trajectory_pass.tum
gate:
  min_auc: 0.95
  max_chamfer: 0.05
  max_ate: 0.30
  max_rpe: 0.20
  max_drift: 0.50
  min_coverage: 0.90
"""


def build(output_dir: Path) -> None:
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    map_ref = _planar_map()
    timestamps, traj_ref = _figure8_trajectory()

    _write_pcd(map_ref, output_dir / "reference" / "map.pcd")
    _write_tum(timestamps, traj_ref, output_dir / "reference" / "trajectory.tum")

    # Sample passing output: reference + small noise. Determinism via fixed seed.
    rng = np.random.default_rng(7)
    map_pass = map_ref + rng.normal(0, 0.02, size=map_ref.shape)
    traj_pass = traj_ref + rng.normal(0, 0.05, size=traj_ref.shape)

    _write_pcd(map_pass, output_dir / "sample_outputs" / "map_pass.pcd")
    _write_tum(timestamps, traj_pass, output_dir / "sample_outputs" / "trajectory_pass.tum")

    (output_dir / "suite.yaml").write_text(SUITE_YAML, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Output directory for the synthetic-figure8 suite",
    )
    args = parser.parse_args()
    build(args.output)
    print(f"Wrote synthetic-figure8 suite to {args.output}")


if __name__ == "__main__":
    main()
