#!/usr/bin/env python3
"""Build a public static demo bundle for GitHub Pages."""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

import numpy as np
import open3d as o3d

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = REPO_ROOT / "cloudanalyzer"
if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))

from public_benchmark_assets import (
    HDL_LOCALIZATION_MAP_PAGE,
    HDL_LOCALIZATION_MAP_URL,
    HDL_LOCALIZATION_REPO_URL,
    download_hdl_localization_map,
    make_trajectory_rows,
    write_csv_trajectory,
)
from ca.web import export_static_bundle


def build_public_demo(output_dir: Path, max_points: int) -> dict:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_root = Path(tmp_dir)
        map_path = download_hdl_localization_map(tmp_root)
        reference_cloud = o3d.io.read_point_cloud(str(map_path))
        if len(reference_cloud.points) == 0:
            raise RuntimeError("failed to load hdl_localization sample map")

        reference_points = np.asarray(reference_cloud.points, dtype=float)
        center = reference_points.mean(axis=0)
        extent = reference_points.max(axis=0) - reference_points.min(axis=0)

        source_cloud = reference_cloud.voxel_down_sample(voxel_size=0.2)
        source_points = np.asarray(source_cloud.points, dtype=float).copy()
        source_points[:, 0] += 0.08
        source_points[:, 1] -= 0.04
        source_points[:, 2] += 0.02
        source_cloud = o3d.geometry.PointCloud()
        source_cloud.points = o3d.utility.Vector3dVector(source_points)

        source_path = tmp_root / "hdl_localization_source.pcd"
        reference_path = tmp_root / "hdl_localization_reference.pcd"
        estimated_traj_path = tmp_root / "hdl_localization_traj.csv"
        reference_traj_path = tmp_root / "hdl_localization_traj_ref.csv"

        o3d.io.write_point_cloud(str(source_path), source_cloud)
        o3d.io.write_point_cloud(str(reference_path), reference_cloud)
        write_csv_trajectory(
            estimated_traj_path,
            make_trajectory_rows(
                center,
                extent,
                phase=0.12,
                radial_wobble=0.035,
                vertical_wobble=0.08,
            ),
        )
        write_csv_trajectory(
            reference_traj_path,
            make_trajectory_rows(
                center,
                extent,
                phase=0.0,
                radial_wobble=0.0,
                vertical_wobble=0.05,
            ),
        )

        result = export_static_bundle(
            [str(source_path), str(reference_path)],
            output_dir=str(output_dir),
            max_points=max_points,
            heatmap=True,
            trajectory_path=str(estimated_traj_path),
            trajectory_reference_path=str(reference_traj_path),
            trajectory_max_time_delta=0.2,
        )

    attribution = "\n".join(
        [
            "# hdl_localization Map Demo Attribution",
            "",
            "Source map: public sample global map bundled in koide3/hdl_localization.",
            f"Source repository: {HDL_LOCALIZATION_REPO_URL}",
            f"Source file: {HDL_LOCALIZATION_MAP_PAGE}",
            f"Raw file URL: {HDL_LOCALIZATION_MAP_URL}",
            "",
            "The reference cloud is the original sample map.",
            "The source cloud is a 0.2m voxel-downsampled derivative with a small rigid offset",
            "to make the heatmap and overlay inspection meaningful in a static viewer.",
            "Both trajectories are generated by CloudAnalyzer to demonstrate trajectory overlays.",
            "",
            "The hdl_localization repository is BSD-2-Clause.",
            "The sample map is published by AISL at Toyohashi University of Technology.",
        ]
    )
    (output_dir / "ATTRIBUTION.md").write_text(attribution + "\n")
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the public hdl_localization map demo bundle.")
    parser.add_argument(
        "--output",
        default="docs/demo/hdl-localization-map",
        help="Output directory for the static viewer bundle",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=50_000,
        help="Viewer point budget passed to ca web-export",
    )
    args = parser.parse_args()

    result = build_public_demo(Path(args.output), max_points=args.max_points)
    print(f"Exported:     {result['output_dir']}")
    print(f"Viewer mode:  {result['viewer_mode']}")
    print(f"Data:         {result['data_json']}")
    print(f"Chunks:       {result['chunk_count']}")
    print(f"Display pts:  {result['display_points']}")


if __name__ == "__main__":
    main()
