"""Add inspected gap drafts without replacing retained lanes or directed routes."""
from __future__ import annotations

import copy
import json
import os
import tempfile
from pathlib import Path
from typing import Any, cast

import numpy as np
from scipy.spatial import cKDTree

from ca import mapping_job as jobs, mapping_retry as retries
from ca.mapping_connections import edges, route_metrics
from ca.mapping_geometry import verify_lane_roundtrip
from ca.vector_map import _publish


def _read(artifact: dict[str, Any]) -> dict[str, Any]:
    jobs._verify(artifact)
    return cast(dict[str, Any], json.loads(Path(artifact["path"]).read_text()))


def _intervals(attempt: dict[str, Any]) -> dict[int, tuple[float, float]]:
    report = _read(attempt["files"]["report"])
    if "lane_intervals" in report:
        return {int(k): tuple(v) for k, v in report["lane_intervals"].items()}
    geometry = _read(attempt["geometry_inputs"]["report"])
    segments = {s["curve_ids"]["center"]: s for s in geometry["segments"]}
    result = {}
    for piece in report["built_segments"]:
        if len(piece["lane_ids"]) != 1:
            raise ValueError("gap patches require one forward lane per source piece")
        segment = segments[piece["center_curve_id"]]
        result[piece["lane_ids"][0]] = (segment["from_m"], segment["to_m"])
    if attempt.get("routes"):
        proposal = _read(attempt["connection_proposal"])
        offered = {(c["from"], c["to"]): c for c in proposal["candidates"]}
        for added in attempt["routes"]["added"]:
            c = offered[added["from"], added["to"]]
            result[added["lane"]] = (c["from_m"], c["to_m"])
    return result


def validate(root: Path, cid: int, gap_ids: Any) -> dict[str, Any]:
    """Validate frozen lineage, seen root gaps and bounded additions before spending."""
    from ca.mapping_run import _load as load_run
    job = jobs._load(root); jobs._inputs(job)
    if "retry_parent" not in job or "gap_patch" in job:
        raise ValueError("one gap patch is available only in a retry child")
    parent_root = Path(job["retry_parent"]["job_dir"])
    parent_job = jobs._load(parent_root); jobs._inputs(parent_job)
    stage = parent_job.get("pointcloud_retry", {})
    if stage.get("status") != "ready" or Path(stage["child_job_dir"]).resolve() != root.resolve():
        raise ValueError("patch child does not match the ready root retry")
    baseline = retries._parent(parent_job, stage["candidate_id"])
    candidate = retries._parent(job, cid)
    run, parent_run = load_run(root), load_run(parent_root)
    if candidate["kind"] != "corridor_lanes" or cid not in [h.get("lane_candidate_id") for h in run["history"]]:
        raise ValueError("patch an unconnected lane draft generated by this retry run")
    if jobs._remaining(job) < 1:
        raise ValueError("a gap patch needs one remaining shared HD attempt")
    if (job["source"] != parent_job["source"] or job["runtime"] != parent_job["runtime"]
        or run["layout_file"]["sha256"] != parent_run["layout_file"]["sha256"]
        or job["minimum_retained_fraction"] != parent_job["minimum_retained_fraction"]
        or any(job["pointcloud"]["files"][k]["sha256"] != parent_job["pointcloud"]["files"][k]["sha256"] for k in ("graph", "trajectory"))):
        raise ValueError("gap patch changed source, runtime, layout or original reference motion")
    proposal, before_proposal = _read(candidate["corridor_proposal"]), _read(baseline["corridor_proposal"])
    if proposal["protocol"] != before_proposal["protocol"] or candidate["extent"]["trajectory_length_m"] != baseline["extent"]["trajectory_length_m"]:
        raise ValueError("gap patch changed source protocol or original station denominator")
    layout = _read(run["layout_file"])
    if len(layout["lanes"]) != 1 or layout["lanes"][0]["direction"] != "forward" or not layout["lanes"][0]["one_way"]:
        raise ValueError("gap patches currently require one forward one-way lane")
    if any(spec["lanes"] != layout["lanes"] or spec["speed_limit_kmh"] != layout["speed_limit_kmh"] for a in (baseline, candidate) for spec in a["road_options"]["lane_specs"]):
        raise ValueError("gap patch lane hypotheses differ from the fixed run layout")
    receipts = [h["gap_observation"] for h in parent_run["history"] if h.get("gap_observation", {}).get("candidate_id") == baseline["id"]]
    if not receipts:
        raise ValueError("inspect root baseline gaps before patching")
    evidence = receipts[-1]["file"]
    gaps = _read(evidence); retries._verify_inputs(gaps["inputs"])
    seen = {g["id"] for receipt in receipts if receipt["file"] == evidence for g in receipt["gaps"]}
    if not isinstance(gap_ids, list) or not 1 <= len(gap_ids) <= 32 or any(type(i) is not int for i in gap_ids) or len(set(gap_ids)) != len(gap_ids) or not set(gap_ids) <= seen:
        raise ValueError("choose 1..32 distinct gap IDs inspected through the root run")
    chosen = [g for g in gaps["gaps"] if g["id"] in gap_ids]
    original, trial = _read(baseline["files"]["editable_map"]), _read(candidate["files"]["editable_map"])
    if any(trial.get(k) for k in ("roads", "rules", "topology", "signals", "crosswalks", "markings")):
        raise ValueError("patch additions must be isolated source-lane drafts without relations")
    before, additions = _intervals(baseline), _intervals(candidate)
    if not 1 <= len(additions) <= 32 or len(before) + len(additions) > 256:
        raise ValueError("gap patches allow 1..32 new lanes and at most 256 total lanes")
    # Validate route-to-source accounting, including original connector intervals.
    route_metrics(original, before); route_metrics(trial, additions)
    for lo, hi in additions.values():
        cuts = sorted({lo, hi, *[v for g in chosen for v in (g["from_m"], g["to_m"]) if lo < v < hi]})
        if any(not any(g["from_m"] <= a and b <= g["to_m"] for g in chosen) for a, b in zip(cuts, cuts[1:])):
            raise ValueError("every added lane must lie entirely inside selected root gaps")
        if any(max(lo, a) < min(hi, b) - 1e-9 for a, b in before.values()):
            raise ValueError("gap patch would overlap a retained lane or connector station interval")
    inputs = {"gap_evidence": evidence, "root_layout": parent_run["layout_file"], "child_layout": run["layout_file"],
              **{f"baseline_{k}": v for k, v in baseline["files"].items()}, "baseline_audits": baseline["quality_report"],
              **{f"baseline_geometry_{k}": v for k, v in baseline["geometry_inputs"].items()},
              **{f"baseline_connection_{k}": v for k, v in baseline.get("connection_inputs", {}).items()},
              "baseline_proposal": baseline["corridor_proposal"],
              **{f"addition_{k}": v for k, v in candidate["files"].items()}, "addition_audits": candidate["quality_report"],
              **{f"addition_geometry_{k}": v for k, v in candidate["geometry_inputs"].items()},
              "addition_proposal": candidate["corridor_proposal"],
              **{f"baseline_pointcloud_{k}": v for k, v in parent_job["pointcloud"]["files"].items()},
              **{f"trial_pointcloud_{k}": v for k, v in job["pointcloud"]["files"].items()}}
    if "connection_proposal" in baseline:
        inputs["baseline_connection_proposal"] = baseline["connection_proposal"]
    retries._verify_inputs(inputs)
    return {"inputs": inputs, "baseline": baseline, "candidate": candidate, "original": original, "trial": trial,
            "before_intervals": before, "addition_intervals": additions, "chosen_gaps": chosen}


def _merge(original: dict[str, Any], trial: dict[str, Any]) -> tuple[dict[str, Any], dict[int, int]]:
    result = copy.deepcopy(original)
    maximum = max(item["id"] for key in ("lanes", "boundaries", "roads", "rules") for item in original.get(key, []))
    mapping = {}
    for boundary in trial["boundaries"]:
        maximum += 1; mapping[boundary["id"]] = maximum
        result.setdefault("boundaries", []).append({**copy.deepcopy(boundary), "id": maximum})
    lane_ids = {}
    for source in trial["lanes"]:
        maximum += 1; lane_ids[source["id"]] = maximum
        lane = copy.deepcopy(source); lane["id"] = maximum
        for side in ("left", "right"):
            ref = lane[side]
            lane[side] = mapping[ref] if type(ref) is int else {**ref, "boundary": mapping[ref["boundary"]]}
        result["lanes"].append(lane)
    return result, lane_ids


def preview(root: Path, cid: int, gap_ids: list[int], offset: int) -> dict[str, Any]:
    if type(offset) is not int or offset < 0:
        raise ValueError("patch preview offset must be nonnegative")
    prepared = validate(root, cid, gap_ids)
    merged, mapping = _merge(prepared["original"], prepared["trial"])
    intervals = {**prepared["before_intervals"], **{mapping[i]: pair for i, pair in prepared["addition_intervals"].items()}}
    names = {i: f"baseline:{i}" for i in prepared["before_intervals"]}
    names.update({v: f"addition:{k}" for k, v in mapping.items()})
    boundaries = {b["id"]: b["geometry"] for b in merged["boundaries"]}
    def curve(lane: dict[str, Any], side: str) -> np.ndarray:
        ref = lane[side]
        points = np.asarray(boundaries[ref if type(ref) is int else ref["boundary"]])
        return points[::-1] if isinstance(ref, dict) and ref.get("reversed", False) else points
    pairs, holds = [], []
    for first in merged["lanes"]:
        for second in merged["lanes"]:
            if first["id"] == second["id"] or not {first["id"], second["id"]} & set(mapping.values()):
                continue
            distances = [float(np.linalg.norm(curve(first, side)[-1] - curve(second, side)[0])) for side in ("left", "right")]
            if max(distances) > .01:
                continue
            if abs(intervals[first["id"]][1] - intervals[second["id"]][0]) > 1e-6:
                holds.append("geometric_endpoint_link_outside_original_station_adjacency")
                continue
            pairs.append({"from": names[first["id"]], "to": names[second["id"]],
                          "from_lane": first["id"], "to_lane": second["id"],
                          "station_m": intervals[first["id"]][1], "boundary_endpoint_distances_m": distances})
    expected = edges(prepared["original"]) | {(p["from_lane"], p["to_lane"]) for p in pairs}
    trial = copy.deepcopy(merged)
    trial["topology"] = [{"lane": i, "successors": sorted(b for a, b in expected if a == i),
                          "predecessors": sorted(a for a, b in expected if b == i)} for i in sorted(intervals)]
    try:
        routes = route_metrics(trial, intervals)
    except ValueError:
        routes = None; holds.append("ambiguous_or_noncontiguous_endpoint_links")
    report = {"candidate_id": cid, "gap_ids": gap_ids, "inputs": prepared["inputs"], "pairs": pairs,
              "addition_lane_id_map": {str(k): v for k, v in mapping.items()},
              "addition_intervals": {str(k): list(v) for k, v in prepared["addition_intervals"].items()},
              "baseline_routes": route_metrics(prepared["original"], prepared["before_intervals"]),
              "proposed_routes": routes, "holds": sorted(set(holds)),
              "note": "Exact geometric endpoint links can be inferred by the OSM reader. Inspect and explicitly adopt every offered pair, or revise the addition draft. Original connections remain fixed. These links do not establish legal routing."}
    path = root / f"patch-preview-{cid:02d}.json"
    if path.exists():
        saved = json.loads(path.read_text())
        if saved != report:
            raise ValueError("retained patch preview inputs or selected gaps changed")
    else:
        jobs._save(path, report)
    retries._verify_inputs(report["inputs"])
    return {"file": jobs._artifact(path), "candidate_id": cid, "gap_ids": gap_ids, "pairs": pairs[offset:offset + 8],
            "pairs_total": len(pairs), "next_offset": offset + 8 if offset + 8 < len(pairs) else None,
            "addition_intervals": report["addition_intervals"], "holds": report["holds"], "note": report["note"]}


def validate_pairs(evidence: dict[str, Any], pairs: Any) -> list[tuple[int, int]]:
    report = _read(evidence); retries._verify_inputs(report["inputs"])
    if report["holds"]:
        raise ValueError("patch preview has held endpoint links")
    if not isinstance(pairs, list) or len(pairs) > 64:
        raise ValueError("patch pairs must be a list of at most 64 explicit decisions")
    offered = {(p["from"], p["to"]): (p["from_lane"], p["to_lane"]) for p in report["pairs"]}
    selected = set()
    for pair in pairs:
        if not isinstance(pair, dict) or set(pair) != {"from", "to", "reason"} or any(not isinstance(pair[k], str) for k in ("from", "to", "reason")) or not pair["reason"].strip():
            raise ValueError("patch pairs need inspected from/to references and a reason")
        key = pair["from"], pair["to"]
        if key not in offered or key in selected:
            raise ValueError("choose distinct inspected patch endpoint pairs")
        selected.add(key)
    if selected != offered.keys():
        raise ValueError("explicitly adopt every implicit endpoint pair or revise the addition draft")
    return [offered[key] for key in sorted(selected)]


def _preserved(original: dict[str, Any], current: dict[str, Any], extra_edges: set[tuple[int, int]] | None = None) -> None:
    for key, value in original.items():
        if key in ("lanes", "boundaries", "roads", "rules"):
            by_id = {item["id"]: item for item in current.get(key, [])}
            if any(by_id.get(item["id"]) != item for item in value):
                raise ValueError("gap patch changed retained map geometry, IDs or semantics")
        elif key != "topology" and current.get(key, [] if isinstance(value, list) else None) != value:
            raise ValueError("gap patch changed retained metadata or topology")
    if edges(original) | (extra_edges or set()) != edges(current):
        raise ValueError("gap patch changed original directed connections")
    links = {row["lane"]: row for row in current.get("topology", [])}
    for row in original.get("topology", []):
        if any(links.get(row["lane"], {}).get(k) != v for k, v in row.items() if k not in {"predecessors", "successors", "lane"}):
            raise ValueError("gap patch changed retained lateral or other lane relationships")


def _audits(saved: dict[str, Any]) -> dict[str, Any]:
    return {"editable": saved["editable"], "reopened_osm": saved["reopened_osm"],
            **{f"consensus_{k}": v for k, v in saved["ground_consensus"].items()}}


def _checks(before: dict[str, Any], after: dict[str, Any], old_ids: set[int], new_ids: set[int]) -> dict[str, Any]:
    """Reject new failures at previously supported old samples, not just net totals."""
    holds = []
    old, new = _audits(before), _audits(after)
    for a, b in (("editable", "reopened_osm"), ("consensus_editable", "consensus_reopened_osm")):
        if jobs._diagnose_audit(new[a])["lanes"] != jobs._diagnose_audit(new[b])["lanes"]:
            holds.append(f"{a}:ir_and_reopened_source_samples_differ")
    for name in ("editable", "reopened_osm", "consensus_editable", "consensus_reopened_osm"):
        a, b = old[name], new[name]; da, db = jobs._diagnose_audit(a), jobs._diagnose_audit(b)
        if not da["complete"] or not db["complete"] or da["protocol"] != db["protocol"] or a["quality"].get("problems_limited", True) or b["quality"].get("problems_limited", True):
            holds.append(f"{name}:incomplete_or_changed_audit_protocol_or_locations"); continue
        rows = [{l["lane"]: l for l in audit["quality"]["lanes"]} for audit in (a, b)]
        if rows[0].keys() != old_ids or rows[1].keys() != old_ids | new_ids:
            holds.append(f"{name}:lane_audit_membership_changed"); continue
        for lid in old_ids:
            for trace in ("center", "left", "right"):
                x, y = rows[0][lid][trace], rows[1][lid][trace]
                if (x["samples"] != y["samples"] or y["supported"] < x["supported"]
                    or any(y[k] > x[k] for k in ("height_mismatches", "insufficient_returns"))
                    or any(x[k] and not y[k] for k in ("start_supported", "end_supported"))):
                    holds.append(f"{name}:retained_trace_regressed:{lid}:{trace}")
        # Full problem locations are required. A net improvement cannot hide a new
        # failure elsewhere on the same unchanged curve or switch failure reasons.
        problems: dict[tuple[int, str, str], list[Any]] = {}
        for p in a["quality"]["problems"]:
            problems.setdefault((p["lane"], p["curve"], p["reason"]), []).extend(p["points"])
        for p in b["quality"]["problems"]:
            if p["lane"] not in old_ids: continue
            known = problems.get((p["lane"], p["curve"], p["reason"]), [])
            if not known or np.any(cKDTree(known).query(p["points"])[0] > 1e-8):
                holds.append(f"{name}:new_retained_failure_location:{p['lane']}:{p['curve']}")
        for lid in new_ids:
            if any(t["supported"] != t["samples"] or not t["start_supported"] or not t["end_supported"] for t in (rows[1][lid][k] for k in ("center", "left", "right"))):
                holds.append(f"{name}:new_lane_not_fully_supported:{lid}")
    return {"protocol": "fixed_four_audits_no_new_retained_failure_locations_new_traces_fully_supported",
            "holds": sorted(set(holds)), "passes": not holds,
            "independent_accuracy_established": False, "road_semantics_verified": False}


def patch(root: Path, cid: int, gap_ids: list[int], pairs: list[dict[str, Any]], preview_file: dict[str, Any], reason: str, prepared: dict[str, Any]) -> dict[str, Any]:
    with jobs._locked(root):
        job = jobs._load(root); jobs._inputs(job)
        validated = validate(root, cid, gap_ids)
        if validated["inputs"] != prepared["inputs"]:
            raise ValueError("gap patch inputs changed after decision validation")
        offered = _read(preview_file)
        if offered["candidate_id"] != cid or offered["gap_ids"] != gap_ids or offered["inputs"] != prepared["inputs"]:
            raise ValueError("patch preview belongs to another decision")
        chosen_pairs = validate_pairs(preview_file, pairs)
        baseline, addition = validated["baseline"], validated["candidate"]
        attempt: dict[str, Any] = {"id": len(job["attempts"]) + 1, "kind": "patched_corridor_lanes", "status": "running",
            "reason": reason, "parent_candidate_id": cid, "gap_ids": gap_ids, "patch_inputs": prepared["inputs"], "patch_pairs": pairs, "patch_preview": preview_file,
            "geometry_inputs": addition["geometry_inputs"], "corridor_proposal": addition["corridor_proposal"], "road_options": addition["road_options"]}
        job["attempts"].append(attempt); job["gap_patch"] = {"candidate_id": attempt["id"], "gap_ids": gap_ids}
        jobs._save(root / "job.json", job)
        target = root / f"candidate-{attempt['id']:02d}"
        try:
            if target.exists(): raise FileExistsError(str(target))
            ir, ids = _merge(validated["original"], validated["trial"])
            extra_edges = set(chosen_pairs)
            expected_edges = edges(validated["original"]) | extra_edges
            if expected_edges:
                ir["topology"] = [{"lane": i, "successors": sorted(b for a, b in expected_edges if a == i), "predecessors": sorted(a for a, b in expected_edges if b == i)} for i in sorted({l["id"] for l in ir["lanes"]})]
            _preserved(validated["original"], ir, extra_edges)
            intervals = {**validated["before_intervals"], **{ids[i]: pair for i, pair in validated["addition_intervals"].items()}}
            routes = {"before": route_metrics(validated["original"], validated["before_intervals"]), "after": route_metrics(ir, intervals),
                      "added": [], "retained_edges": sorted(edges(validated["original"])), "new_endpoint_pairs": pairs, "legal_routing_verified": False}
            before_report, addition_report = _read(baseline["files"]["report"]), _read(addition["files"]["report"])
            cuts = sorted({v for report in (before_report, addition_report) for item in report["station_disposition"] for v in (item["from_m"], item["to_m"])})
            disposition = []
            for lo, hi in zip(cuts, cuts[1:]):
                old = next(i for i in before_report["station_disposition"] if i["from_m"] <= lo and hi <= i["to_m"])
                new = next(i for i in addition_report["station_disposition"] if i["from_m"] <= lo and hi <= i["to_m"])
                origin = "baseline" if old["status"] == "included_lane_hypothesis" else "patch" if new["status"] == "included_lane_hypothesis" else "baseline"
                disposition.append({**(new if origin == "patch" else old), "from_m": lo, "to_m": hi, "origin": origin})
            extraction = {**baseline["extraction"], "generated_length": sum(i["to_m"] - i["from_m"] for i in disposition if i["status"] == "included_lane_hypothesis"),
                          "roads": baseline["extraction"]["roads"] + len(ids), "lanes": len(ir["lanes"])}
            with tempfile.TemporaryDirectory(prefix=".mapping-patch-", dir=root) as temporary:
                input_path = Path(temporary) / "merged.json"; jobs._save(input_path, ir)
                module = jobs.core(); assert module is not None
                payload = json.loads(module.edit_vector_map_relations(str(input_path)))
                canonical = json.loads(payload["map_json"]); _preserved(validated["original"], canonical, extra_edges)
                verify_lane_roundtrip(ir, canonical)
                if payload["projector_info"] != Path(baseline["files"]["projector"]["path"]).read_text():
                    raise ValueError("gap patch changed baseline coordinate projection")
                draft = Path(temporary) / "result"; files = _publish(payload, draft)["files"]
                reopened = json.loads(module.edit_vector_map_relations(files["map"]))
                reopened_ir = json.loads(reopened["map_json"]); verify_lane_roundtrip(canonical, reopened_ir)
                if edges(reopened_ir) != edges(ir) or route_metrics(reopened_ir, intervals) != routes["after"] or {l["id"]: l.get("turn_direction") for l in reopened_ir["lanes"]} != {l["id"]: l.get("turn_direction") for l in ir["lanes"]}:
                    raise ValueError("gap patch OSM reload changed original routing or turn labels")
                cloud = job["pointcloud"]["files"]["map"]["path"]
                audits = {k: json.loads(module.audit_vector_map_quality_details(cloud, files[f])) for k, f in (("editable", "editable_map"), ("reopened_osm", "map"))}
                audits["ground_consensus"] = {k: json.loads(module.audit_vector_map_ground_consensus_details(cloud, files[f])) for k, f in (("editable", "editable_map"), ("reopened_osm", "map"))}
                checks = _checks(_read(baseline["quality_report"]), audits, set(validated["before_intervals"]), set(ids.values()))
                # New joins also need supported retained endpoints under every audit.
                for name, audit in _audits(audits).items():
                    lanes = {l["lane"]: l for l in audit["quality"]["lanes"]}
                    for frm, to in chosen_pairs:
                        if any(not lanes[lid][trace][endpoint] for lid, endpoint in ((frm, "end_supported"), (to, "start_supported")) for trace in ("center", "left", "right")):
                            checks["holds"].append(f"{name}:unsupported_join_endpoint:{frm}:{to}")
                checks["passes"] = not checks["holds"]
                audit_path = root / f"candidate-{attempt['id']:02d}-patch-audits.json"; jobs._save(audit_path, audits)
                check_path = root / f"candidate-{attempt['id']:02d}-patch-checks.json"; jobs._save(check_path, checks)
                attempt.update(patch_audits=jobs._artifact(audit_path), patch_checks=jobs._artifact(check_path))
                if not checks["passes"]: raise ValueError("gap patch source checks held the replacement: " + ", ".join(checks["holds"][:8]))
                if any(i["severity"] == "error" for i in payload["report"]["autoware_issues"]): raise ValueError("gap patch has export errors")
                jobs._save(draft / "source-quality.json", audits)
                evidence = payload["report"]
                evidence.update(options=addition["road_options"], reason=reason, patch_inputs=prepared["inputs"], patch_checks=checks,
                    baseline_candidate_id=baseline["id"], addition_candidate_id=cid, selected_gap_ids=gap_ids,
                    added_lane_id_map={str(k): v for k, v in ids.items()}, lane_intervals={str(k): v for k, v in intervals.items()},
                    station_disposition=disposition, extraction=extraction, extent=jobs._extent(extraction, job["minimum_retained_fraction"]),
                    routes=routes, built_segments=addition_report["built_segments"], retained_geometry_and_connections=True,
                    lane_roundtrip_verified=True, topology_roundtrip_verified=True,
                    note="HD changes are confined to selected original-station gaps. Existing geometry, IDs, metadata and directed connections remain fixed. The point cloud is the full fusion trial, not an unchanged-outside-ROI point map. Original failed source samples and semantic holds remain visible; no new retained failure locations are allowed.")
                evidence["files"] = {k: str(target / Path(v).name) for k, v in files.items()}
                evidence["editing"] = {"command": "vectormap", "args": ["mcp", evidence["files"]["map"]]}
                jobs._save(draft / "report.json", evidence)
                result = {"files": {k: {**jobs._artifact(files[k]), "path": v} for k, v in evidence["files"].items()},
                    "quality_report": {**jobs._artifact(draft / "source-quality.json"), "path": str(target / "source-quality.json")},
                    "quality": jobs._quality_summary(audits["editable"]), "reopened_quality": jobs._quality_summary(audits["reopened_osm"]),
                    "ground_consensus_quality": {k: jobs._quality_summary(v) for k, v in audits["ground_consensus"].items()},
                    "extraction": extraction, "extent": evidence["extent"], "export_issues": evidence["autoware_issues"], "routes": routes,
                    "status": "audited_draft"}
                jobs._inputs(job); retries._verify_inputs(prepared["inputs"]); jobs._verify(preview_file)
                os.rename(draft, target)
            attempt.update(result); job["status"] = "candidates_ready" if job["selected"] is None else "selected_draft"
        except BaseException as error:
            attempt.update(status="failed", error=str(error), error_type=type(error).__name__)
            if not isinstance(error, Exception) and not jobs._native_panic(error):
                jobs._save(root / "job.json", job); raise
        jobs._save(root / "job.json", job)
    return jobs.inspect_mapping_job(str(root))
